import Paragraph from '@/components/Paragraph';
import Title from '@/components/Title';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { styled } from 'stitches.config';

const Main = styled('main', {
    margin: 'auto',

    maxWidth: '1024px',
    minHeight: '100vh'
});

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>ui — andresmarpz.com</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Main>
                <h1>ui</h1>
                <Paragraph>
                    Hey! Welcome to my playground. This is a collection of
                    components I have created inspired on some cool and smooth
                    interactions I have seen on the web.
                </Paragraph>

                <br />
                <Title size="normal">Link Preview</Title>
                <Image
                    src="/assets/showcases/link-preview.png"
                    alt=""
                    width={600}
                    height={400}></Image>
            </Main>
        </>
    );
};

export default Home;
