import Paragraph from '@/components/global/Paragraph';
import RightArrow from '@/components/svgs/RightArrow';
import Title from '@/components/global/Title';
import { styled } from '@/stitches.config';
import type { NextPage } from 'next';
import Head from 'next/head';
import NextLink from 'next/link';

const Main = styled('main', {
    margin: 'auto',

    maxWidth: '1024px',
    minHeight: '100vh'
});

const StyledLink = styled('a', {
    textDecoration: 'none',
    cursor: 'pointer'
});

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>ui — andresmarpz.com</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Main>
                <h1>ui</h1>
                <Paragraph>
                    Hey! Welcome to my playground. This is a collection of
                    components I have created inspired on some cool and smooth
                    interactions I have seen on the web.
                </Paragraph>

                <br />
                <NextLink href="/link-preview">
                    <StyledLink>
                        <Title size="normal">
                            Link Preview <RightArrow />
                        </Title>
                    </StyledLink>
                </NextLink>
            </Main>
        </>
    );
};

export default Home;
