import type { NextPage } from 'next';
import Head from 'next/head';
import { styled } from 'stitches.config';

const Main = styled('main', {
    margin: 'auto',

    maxWidth: '1024px',
    minHeight: '100vh'
});

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Main>
                <h1>UI</h1>
            </Main>
        </>
    );
};

export default Home;
